### ISSUE TITLE
Suggest: How to use

### ISSUE THREAD

**Issue by 9527q** [coolcode/tomato-clock#1]
In the `README.md`,  `How to use`，command `tomato.py` will get a errer message.

Use `./tomato.py` is the true way.

I suggest that code at `How to use` should use `./` of any command.

**Comment by Fishbubble** [comment]
> In the `README.md`, `How to use`，command `tomato.py` will get a errer message.
> 
> Use `./tomato.py` is the true way.
> 
> I suggest that code at `How to use` should use `./` of any command.

python3 tomato.py

**Comment by coolcode** [comment]
@9527q @Fishbubble Thanks for your comment.

**Comment by coolcode** [comment]
Fixed in README.md & tomato.py.

**Comment by 9527q** [comment]
Should I close this issue now?

**Comment by coolcode** [comment]
> Should I close this issue now?

Yes sure. Or I will close it if no one reports this issue again.
